stages:
  - build
  - test
  - deploy
  - production

TESTNPM:
  stage: test
  tags:
    - node
  script:
    - npm test

Build Container:
  stage: build
  tags: 
    - docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/Pablokiryu/dashapi .
    - docker push registry.gitlab.com/Pablokiryu/dashapi




Staging:
  stage: deploy
  script:
    - docker login --username=$HEROKU_USR --password=$HEROKU_Auth registry.heroku.com
    - docker tag registry.gitlab.com/Pablokiryu/dashapi:latest registry.heroku.com/pablokiryu/murmuring-wave-13155:latest
    - docker push registry.heroku.com/Pablokiryu/murmuring-wave-13155:latest