image: docker:latest

services:
  - docker:dind
stages:
  - test
  - build
  - deploy
  - production

variables:
    MONGOURI: $MONGOURI
    CONTAINER_IMAGE: registry.gitlab.com/pablokiryu2/dashapi:latest

TESTNPM:
  variables:
    MONGOURI: $MONGOURI_TEST
  image: node:10.9.0
  stage: test
  script:
    - npm install
    - npm test

Build Container:
  stage: build
  tags: 
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/pablokiryu2/dashapi .
    - docker push registry.gitlab.com/pablokiryu2/dashapi
Staging:
  tags: 
    - docker
  services:
    - docker:dind
  stage: deploy
  tags:
    - docker
  only:
    - master
  script:
    - docker login --username=HEROKU_USR --password=$HEROKU_Auth registry.heroku.com
    - docker pull $CONTAINER_IMAGE:staging
    - docker tag $CONTAINER_IMAGE:staging registry.heroku.com/pablokiryu/murmuring-wave-13155/web
    - docker push rregistry.heroku.com/pablokiryu/murmuring-wave-13155/web
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_Auth wingrunr21/alpine-heroku-cli container:release web --app $STAGEAPP

Staging:
  stage: deploy
  tags:
    - docker
  only:
    - master
  when: manual
  script:
    - docker login --username=HEROKU_USR --password=$HEROKU_Auth registry.heroku.com
    - docker pull $CONTAINER_IMAGE:staging
    - docker tag $CONTAINER_IMAGE:staging registry.heroku.com/pablokiryu/dashbapi/web
    - docker push rregistry.heroku.com/pablokiryu/dashbapi/web
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_Auth wingrunr21/alpine-heroku-cli container:release web --app $PRODAPP
