image: docker:latest
stages:
  - test
  - build
  - deploy
  - production
variables:
    MONGOURI: $MONGOURI

TESTNPM:
  variables:
    MONGOURI: $MONGOURI_TEST
  image: node:10.9.0
  stage: test
  script:
    - npm install
    - npm test

Build Container:
  stage: build
  tags: 
    - docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/pablokiryu2/dashapi .
    - docker push registry.gitlab.com/pablokiryu2/dashapi

Staging:
  tags: 
    - docker
  services:
    - docker:dind
  stage: deploy
  script:
    - echo $HEROKU_Auth | docker login --username=$HEROKU_USR --password-stdin registry.heroku.com
    - docker tag registry.gitlab.com/pablokiryu2/dashapi:latest registry.heroku.com/pablokiryu/murmuring-wave-13155:latest
    - docker push registry.heroku.com/Pablokiryu/murmuring-wave-13155:latest

Production:
  tags: 
    - docker
  services:
    - docker:dind
  stage: production
  when: manual
  script:
    - echo $HEROKU_Auth | docker login --username=$HEROKU_USR --password-stdin registry.heroku.com
    - docker tag registry.gitlab.com/Pablokiryu/dashapi:latest registry.heroku.com/pablokiryu/dashbapi:latest
    - docker push registry.heroku.com/Pablokiryu/dashbapi:latest