version: '3'
services:
    dashapi:
        container_name: dashserver
        build: .
        ports:
            - '80:3000'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'    